import { app, BrowserWindow, session } from 'electron'
import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { getSettings } from '../store/settings'

const PARTITION = 'persist:yt-login'
const COOKIE_HOST_RE =
  /(^|\.)(youtube|google|googlevideo|ggpht|ytimg|gstatic|googleusercontent)\./i

/** Auth-ish cookie names — presence means a Google/YouTube session (local only). */
const AUTH_NAME_RE = /^(SID|SSID|HSID|APISID|SAPISID|SIDCC|LOGIN_INFO|__Secure-[13]PSID|__Secure-[13]PSIDTS)$/i

export function cookiesFilePath(): string {
  return join(app.getPath('userData'), 'youtube-cookies.txt')
}

function ensureParent(path: string) {
  const dir = dirname(path)
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true })
}

function cookieDomainOk(domain: string | undefined): boolean {
  if (!domain) return false
  const d = domain.startsWith('.') ? domain.slice(1) : domain
  return COOKIE_HOST_RE.test(`.${d}`)
}

function isAuthCookieName(name: string): boolean {
  return AUTH_NAME_RE.test(name)
}

function cookieStillValid(expirationDate: number | undefined, sessionCookie: boolean): boolean {
  if (sessionCookie || !expirationDate) return true
  return expirationDate * 1000 > Date.now() + 60_000
}

function toNetscapeLine(c: Electron.Cookie): string | null {
  if (!c.name || c.value == null || !cookieDomainOk(c.domain)) return null
  const domain = c.domain!.startsWith('.') ? c.domain! : `.${c.domain}`
  const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE'
  const path = c.path || '/'
  const secure = c.secure ? 'TRUE' : 'FALSE'
  const expires = c.session || !c.expirationDate ? '0' : String(Math.floor(c.expirationDate))
  const value = String(c.value).replace(/[\r\n\t]/g, '')
  return [domain, includeSubdomains, path, secure, expires, c.name, value].join('\t')
}

async function sessionLooksSignedIn(): Promise<boolean> {
  const ses = session.fromPartition(PARTITION)
  const all = await ses.cookies.get({})
  return all.some(
    (c) =>
      isAuthCookieName(c.name) &&
      cookieDomainOk(c.domain) &&
      Boolean(c.value) &&
      cookieStillValid(c.expirationDate, Boolean(c.session)),
  )
}

/** Parse Netscape jar; true only if a non-expired auth cookie exists. */
export function jarHasValidAuthCookies(): boolean {
  const path = cookiesFilePath()
  if (!existsSync(path)) return false
  try {
    const text = readFileSync(path, 'utf-8')
    const nowSec = Math.floor(Date.now() / 1000)
    let found = false
    for (const line of text.split(/\r?\n/)) {
      if (!line || line.startsWith('#')) continue
      const parts = line.split('\t')
      if (parts.length < 7) continue
      const name = parts[5]
      const expires = Number(parts[4] || 0)
      if (!isAuthCookieName(name)) continue
      if (expires > 0 && expires < nowSec + 60) continue
      found = true
      break
    }
    return found
  } catch {
    return false
  }
}

export function hasYouTubeCookies(): boolean {
  return jarHasValidAuthCookies()
}

export async function exportYouTubeCookies(): Promise<boolean> {
  const ses = session.fromPartition(PARTITION)
  const all = await ses.cookies.get({})
  const lines = all.map(toNetscapeLine).filter((x): x is string => Boolean(x))
  if (lines.length === 0) return false
  const path = cookiesFilePath()
  ensureParent(path)
  const body = [
    '# Netscape HTTP Cookie File',
    '# Generated by ShiftGrab — local YouTube session only (never uploaded)',
    '',
    ...lines,
    '',
  ].join('\n')
  writeFileSync(path, body, 'utf-8')
  return jarHasValidAuthCookies()
}

export async function clearYouTubeLogin(): Promise<void> {
  const path = cookiesFilePath()
  if (existsSync(path)) {
    try {
      unlinkSync(path)
    } catch {
      /* ignore */
    }
  }
  try {
    const ses = session.fromPartition(PARTITION)
    await ses.clearStorageData({ storages: ['cookies'] })
  } catch {
    /* ignore */
  }
}

/**
 * Re-sync from in-app session; drop expired jar so UI shows Signed out.
 * Never sends cookies off-device.
 */
export async function youtubeAuthStatus(): Promise<{ signedIn: boolean }> {
  try {
    if (await sessionLooksSignedIn()) {
      await exportYouTubeCookies()
    }
  } catch {
    /* ignore */
  }
  if (!jarHasValidAuthCookies()) {
    const path = cookiesFilePath()
    if (existsSync(path)) {
      try {
        unlinkSync(path)
      } catch {
        /* ignore */
      }
    }
    return { signedIn: false }
  }
  return { signedIn: true }
}

/**
 * yt-dlp args: prefer saved Netscape jar; else optional Chrome cookies.
 */
export function cookiesArgs(): string[] {
  const path = cookiesFilePath()
  if (jarHasValidAuthCookies()) {
    return ['--cookies', path]
  }
  const settings = getSettings()
  if (settings.useBrowserCookiesFallback === false) return []
  return ['--cookies-from-browser', 'chrome']
}

let loginWindow: BrowserWindow | null = null
let loginPromise: Promise<{ signedIn: boolean }> | null = null

export function openYouTubeLogin(parent: BrowserWindow | null): Promise<{ signedIn: boolean }> {
  if (loginPromise) {
    if (loginWindow && !loginWindow.isDestroyed()) loginWindow.focus()
    return loginPromise
  }

  loginPromise = new Promise((resolve) => {
    let settled = false
    const win = new BrowserWindow({
      width: 980,
      height: 740,
      minWidth: 720,
      minHeight: 560,
      parent: parent || undefined,
      modal: false,
      show: false,
      autoHideMenuBar: true,
      title: 'Sign in to YouTube — closes automatically when done',
      backgroundColor: '#0f1419',
      webPreferences: {
        partition: PARTITION,
        nodeIntegration: false,
        contextIsolation: true,
        sandbox: true,
      },
    })
    loginWindow = win

    const finish = async () => {
      if (settled) return
      settled = true
      if (poll) clearInterval(poll)
      loginWindow = null
      loginPromise = null
      try {
        await exportYouTubeCookies()
      } catch {
        /* ignore */
      }
      resolve(await youtubeAuthStatus())
    }

    const poll = setInterval(() => {
      void (async () => {
        if (win.isDestroyed() || settled) return
        try {
          if (await sessionLooksSignedIn()) {
            await exportYouTubeCookies()
            if (!win.isDestroyed()) win.close()
          }
        } catch {
          /* keep polling */
        }
      })()
    }, 1500)

    win.on('closed', () => {
      void finish()
    })

    win.once('ready-to-show', () => win.show())
    void win.loadURL('https://www.youtube.com/account')
  })

  return loginPromise
}
